import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { DesktopNavBar, MobileNavBar } from "@/components/navbars";
import { ThemeProvider } from "@/components/ui/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div>
        <MobileNavBar />
        <DesktopNavBar />
        {children}
      </div>
  );
}
