# Generated by Django 5.0.4 on 2024-04-06 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_options_transaction_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedfunds',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignedFunds', to='api.organization'),
            preserve_default=False,
        ),
    ]
