# Generated by Django 5.0.4 on 2024-04-06 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assignedfunds_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedfunds',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_funds', to='api.expense'),
        ),
    ]
