# Generated by Django 5.0.4 on 2024-04-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_assignedfunds_expense_balance_in_cents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='cbu',
            field=models.CharField(default='0000000000000000000000', max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cuit',
            field=models.CharField(default='00000000000', max_length=11, unique=True),
        ),
    ]
