# Generated by Django 5.0.4 on 2024-04-07 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_supplier_cbu_alter_supplier_cuit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='state',
            new_name='status',
        ),
    ]
