# Generated by Django 5.0.4 on 2024-04-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_state_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.CharField(default='avatar-default.jpg', max_length=100),
        ),
    ]
